FROM php:apache

WORKDIR /var/www/html

RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    unzip
    
RUN docker-php-ext-install mysqli pdo_mysql && docker-php-ext-enable mysqli

EXPOSE 80

CMD ["apache2-foreground"]